spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresdb:5432/submissiondata
    username: postgres
    password: password
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    out-of-order: false
  rabbitmq: 
    host: rabbitmq
    username: rabbitmq
    password: rabbitmq
    port: 5672
    virtual-host: /

logging:
  level:
    com.da: INFO
    org.springframework.web: INFO

rabbitmq:
  exchange:
    name: ${SPRING_PROFILES_ACTIVE:local}
  routing-key:
    email-submission-notification: email.submission.notification
    email-submission-ack: emails.submission.ack