spring:
  rabbitmq: 
    host: rabbitmq
    username: rabbitmq
    password: rabbitmq
    port: 5672
    virtual-host: /
  mail: 
    host: smtp.office365.com
    password: DentistMove2021!
    port: 587
    properties: 
      mail: 
        smtp: 
          auth: true
          connectiontimeout: 5000
          socketFactory: 
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls: 
            enabled: true
          timeout: 5000
          writetimeout: 5000
    username: movedentist

logging:
  level:
    com.da: INFO
    org.springframework.web: INFO

rabbitmq:
  dead-letter:
    name: "dlq"
  email:
    queue: email
    routing-keys: email.submission.notification
    durable: true
    dead-letter:
      routing-key: email.dlq

email:
  smtp:
    host: "smtp.office365.com"
    port: 587
    auth: "true"
    start-tls-enable: "true"
  account:
    username: "movedentist@outlook.com"
    password: ${email_smtp_password}
